ifeq ($(MODE),zero)
############################### GNU compiler
CC = gcc
LD = gcc
HDF_INCLUDE = 
HDF_LIB = 
COPTS = -g -fPIC -D_GNU_SOURCE -O0 -Wall -Wstrict-aliasing  -fstrict-aliasing
###############################
endif

ifeq ($(MODE),one)
################################# Portland Group compiler
HDF_INCLUDE =
HDF_LIB =
COPTS = -g -fPIC -D_GNU_SOURCE -O2 -Minform=inform -Mlarge_arrays
###############################
endif

